// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGtOAgiMl2z7YrmmGFoQLLAk4jJIBDu-I',
    appId: '1:443853206139:web:86d00aeedb0e485043a8de',
    messagingSenderId: '443853206139',
    projectId: 'bezalelai',
    authDomain: 'bezalelai.firebaseapp.com',
    databaseURL: 'https://bezalelai-default-rtdb.firebaseio.com',
    storageBucket: 'bezalelai.appspot.com',
    measurementId: 'G-GQWPLD25X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLCHmUVXd3Sapyz2rzHyKm9gIekNF_s94',
    appId: '1:443853206139:android:2a5721387c4e0f7643a8de',
    messagingSenderId: '443853206139',
    projectId: 'bezalelai',
    databaseURL: 'https://bezalelai-default-rtdb.firebaseio.com',
    storageBucket: 'bezalelai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0XUogjgJKHOmmNeHNA7sX7Lg3KAzb8N8',
    appId: '1:443853206139:ios:8a0db31c1d52fdf243a8de',
    messagingSenderId: '443853206139',
    projectId: 'bezalelai',
    databaseURL: 'https://bezalelai-default-rtdb.firebaseio.com',
    storageBucket: 'bezalelai.appspot.com',
    iosBundleId: 'com.example.newbeza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0XUogjgJKHOmmNeHNA7sX7Lg3KAzb8N8',
    appId: '1:443853206139:ios:8a0db31c1d52fdf243a8de',
    messagingSenderId: '443853206139',
    projectId: 'bezalelai',
    databaseURL: 'https://bezalelai-default-rtdb.firebaseio.com',
    storageBucket: 'bezalelai.appspot.com',
    iosBundleId: 'com.example.newbeza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGtOAgiMl2z7YrmmGFoQLLAk4jJIBDu-I',
    appId: '1:443853206139:web:17c89071c499cc7943a8de',
    messagingSenderId: '443853206139',
    projectId: 'bezalelai',
    authDomain: 'bezalelai.firebaseapp.com',
    databaseURL: 'https://bezalelai-default-rtdb.firebaseio.com',
    storageBucket: 'bezalelai.appspot.com',
    measurementId: 'G-23CGTYZBQ5',
  );
}
